# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.cache/wt [current_project]
set_property parent.project_path E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files e:/Computer_composition/SSCPUEX_SOC/sutudentnosortion.coe
read_verilog -library xil_defaultlib {
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/EXT.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/课用/大二下/计算机组成原理/要求/code/source/source/SCCPU_FPGATop/MIO_BUS.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/课用/大二下/计算机组成原理/要求/code/source/source/SCCPU_FPGATop/Multi_CH32.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/ctrl_encode_def.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/NPC.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/PC.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/RF.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/alu.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/课用/大二下/计算机组成原理/要求/code/source/source/SCCPU_FPGATop/clk_div.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/ctrl.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/课用/大二下/计算机组成原理/要求/code/source/source/SCCPU_FPGATop/dm.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/mux.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/Computer_composition/SCCPUEX/sccpu.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/课用/大二下/计算机组成原理/要求/code/source/source/SCCPU_FPGATop/seg7x16.v
  E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/imports/课用/大二下/计算机组成原理/要求/code/source/source/SCCPU_FPGATop/SCCPU_Top.v
}
read_ip -quiet e:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all e:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/sources_1/ip/imem/imem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/constrs_1/imports/source/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files E:/Computer_composition/SSCPUEX_SOC/SSCPUEX_SOC/SSCPUEX_SOC.srcs/constrs_1/imports/source/Nexys4DDR_CPU.xdc]


synth_design -top SCCPUSOC_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SCCPUSOC_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SCCPUSOC_Top_utilization_synth.rpt -pb SCCPUSOC_Top_utilization_synth.pb"
